language: python
python:
  - "2.7"

# command to install dependencies
install: "pip install -r requirements.txt"

before_script: 
  - psql -c 'create database shoppingcart;' -U postgres

script:
  - nosetests

#after_success:
  - codecov

services:
  - postgresql

env:
  global:
    - DB_HOST=127.0.0.1
    - DB_NAME=shoppingcart
    - DB_USER=postgres
    - DB_PASSWORD=


